#ifndef PIN_SETTINGS_H
#define PIN_SETTINGS_H

#include <avr/io.h>

// 스위치 핀 설정
#define SWITCH_BASE PINE
#define SWITCH_DDR DDRE
#define SWITCH1_BIT PINE3
#define SWITCH2_BIT PINE4
#define SWITCH_ALL_BITS (PINE3 | PINE4)

// LED 핀 설정
#define LED_BASE PORTA
#define LED_DDR DDRA
#define LED0_BIT PINA0
#define LED1_BIT PINA1
#define LED2_BIT PINA2
#define LED3_BIT PINA3
#define LED4_BIT PINA4
#define LED5_BIT PINA5
#define LED6_BIT PINA6
#define LED7_BIT PINA7
#define LED_ALL_BITS (PINA0 | PINA1 | PINA2 | PINA3 | PINA4 | PINA5 | PINA6 | PINA7)

// FND 핀 설정
#define FND_DATA_BASE PORTC
#define FND_DATA_DDR DDRC
#define FND_DATA0_BIT PINC0
#define FND_DATA1_BIT PINC1
#define FND_DATA2_BIT PINC2
#define FND_DATA3_BIT PINC3
#define FND_DATA4_BIT PINC4
#define FND_DATA5_BIT PINC5
#define FND_DATA6_BIT PINC6
#define FND_DATA7_BIT PINC7
#define FND_DATA_ALL_BITS (PINC0 | PINC1 | PINC2 | PINC3 | PINC4 | PINC5 | PINC6 | PINC7)

// FND 선택 핀 설정
#define FND_SELECT_BASE PORTG
#define FND_SELECT_DDR DDRG
#define FND_SELECT0_BIT PING0
#define FND_SELECT1_BIT PING1
#define FND_SELECT2_BIT PING2
#define FND_SELECT3_BIT PING3
#define FND_SELECT_ALL_BITS (PING0 | PING1 | PING2 | PING3)

// 부저 핀 설정
#define BUZZER_BASE PORTB
#define BUZZER_DDR DDRB
#define BUZZER_BIT PINB4

// ADC 핀 설정
#define CDS_BIT PINF0
#define SOUND_SENSOR_BIT PINF2

// 로터리 엔코더 핀 설정
#define ROTARY_ENCODER_BASE PINE
#define ROTARY_ENCODER_DDR DDRE
#define ROTARY_ENCODER_S1_BIT PINE3
#define ROTARY_ENCODER_S2_BIT PINE2
#define ROTARY_ENCODER_ALL_BITS (PINE2 | PINE3)

// RGB LED 핀 설정
#define RGB_LED_BASE PORTB
#define RGB_LED_DDR DDRB
#define RGB_LED_R_BIT PINB5
#define RGB_LED_G_BIT PINB6
#define RGB_LED_B_BIT PINB7
#define RGB_LED_ALL_BITS (PINB5 | PINB6 | PINB7)

#endif